adds relational data model/SQL import docs
archesproject/arches-docs pull request #276
Opened 2022-02-25 22:04 UTC by robgaston

Adds the documentation for using the functions to create relational views of Arches graph schema.

@mradamcox do you have any recommendations as far as the way that I documented these functions? I wasn't really certain about the best conventions to use for documenting SQL functions, so I just gave it a shot.

2022-03-04 18:06 UTC, mradamcox requested changes
Hi @robgaston this looks great overall, I just wanted to ask: could you throw in one example of what it would look like to run one of these functions? Would you use psql? Write a one-off `.sql` file? Just a code-block example where we can see what it looks like to feed in the arguments and get the return (I've never used one of these). I have some other formatting ideas, but I'll take care of that when the content is all ready to merge.

2022-05-10 20:49 UTC, robgaston commented
@mradamcox you can use any SQL client you like (I use vscode, but psql or pgadmin should work just fine) to execute these functions.

An example usage that I've found handy is to create a schema for every active resource model:
```sql
select __arches_create_resource_model_views(graphid) from graphs
  where isactive = true
  and name != 'Arches System Settings';
```

2022-07-20 19:39 UTC, mradamcox approved these changes

2022-07-20 20:15 UTC, mradamcox commented
Merging this in now. I think the example I added may still need a look over, but in general I think it's very close, and this content is good overall.

2022-07-20 20:15 UTC, merged