Updated css path
archesproject/arches-docs pull request #322
Opened 2023-03-08 18:00 UTC by ekansa

### brief description of changes
Updates a css path for the Overwriting Core Arches Content section

#### issues addressed
(https://github.com/archesproject/arches-docs/issues/321)

#### further comments
@ydrea  Is there anything else we should update here? Is there any impact on behaviors with "collectstatic" etc?

---

This box **must** be checked
- [X] the PR branch was originally made from the base branch

This box **should** be checked
- [X] after these changes the docs build locally without error

This box **should only** be checked you intend to follow through on it (we can do it on our end too)
- [X] I will `cherry-pick` all commits in this PR into other branches that should have them _after_ this PR is merged

2023-03-08 23:25 UTC, mradamcox requested changes
Based on feedback in the original ticket, I think there should be a link here to the `collectstatic` information in the Apache deployment  section.

2023-03-08 23:26 UTC, ekansa commented
@mradamcox Sounds good! I'll make that update

2023-03-08 23:35 UTC, ekansa commented
@mradamcox OK. I made the requested change to link to the `Serving Arches with Apache` page. At some point I'm going to want to make Nginx documentation too.

2023-03-09 18:27 UTC, ekansa commented
@mradamcox OK to merge now?

2023-03-09 18:29 UTC, mradamcox commented
Looks good, thanks for the update!

2023-03-09 18:49 UTC, ekansa commented
Thanks for the review @mradamcox !

2023-03-09 18:49 UTC, merged