update note abot restarting supervisord on reboot
archesproject/arches-docs pull request #399
Opened 2024-02-07 17:50 UTC by mradamcox

### brief description of changes
update note abot restarting supervisord on reboot, see forum post for more context: https://community.archesproject.org/t/startup-supervisor-celery-on-reboot/2115/4

---

This box **must** be checked
- [x] the PR branch was originally made from the base branch

This box **should** be checked
- [ ] after these changes the docs build locally without error

This box **should only** be checked you intend to follow through on it (we can do it on our end too)
- [ ] I will `cherry-pick` all commits in this PR into other branches that should have them _after_ this PR is merged

2024-02-07 19:03 UTC, ekansa requested changes
A few notes about adding some clarification that this involves editing the crontab

2024-02-07 19:03 UTC, ekansa commented on docs/deployment/setting-up-supervisord-for-celery.rst
> +On linux-based systems you can use a cronjob to ensure that supervisor starts whenever your system is rebooted. Note that you'll need to provide the full path to the virtual environment where you ins
We may want to provide a little direction on how to edit the crontab. We want to be very clear that the `@reboot...` goes there.

2024-02-07 19:03 UTC, ekansa commented on docs/deployment/setting-up-supervisord-for-celery.rst
> +
Note that this should be added to the crontab.

2024-02-07 19:23 UTC, mradamcox commented
Good call, I'll make these changes when I can.

2024-04-23 20:50 UTC, ekansa approved these changes
Added update on changing the crontab

2024-04-23 20:50 UTC, merged