commit docs on core search componenets, re #429
archesproject/arches-docs pull request #431
Opened 2024-06-07 21:47 UTC by whatisgalen

### brief description of changes

#### issues addressed

#### further comments

---

This box **must** be checked
- [ ] the PR branch was originally made from the base branch

This box **should** be checked
- [ ] after these changes the docs build locally without error

This box **should only** be checked you intend to follow through on it (we can do it on our end too)
- [ ] I will `cherry-pick` all commits in this PR into other branches that should have them _after_ this PR is merged

2024-06-10 15:43 UTC, ekansa commented
@whatisgalen does this apply to v7.5 (earlier too) or only the upcoming v7.6?

2024-06-12 23:35 UTC, ekansa requested changes
I made a quick edit to include this in the index so the new page can be found. Mainly, it would be good to add a short intro this section to explain the significance of search components. It would also help make this easier to find via a naive full text search of the docs!

2024-06-12 23:35 UTC, ekansa commented on docs/developing/reference/search-components.rst
> +
@whatisgalen this looks really helpful! Can you write a brief intro here about what search components are, what they do, and what can be done with the instructions below to customize search in Arches? Also, it may be good to include a quick bit advice on how to develop search components with an eye toward long term maintainability, especially with Arches version changes.

2024-07-02 13:44 UTC, ekansa commented
@whatisgalen just checking to see if you need any help or clarification with my review request!

2024-07-17 20:50 UTC, ekansa commented on docs/developing/reference/search-components.rst
> +
@whatisgalen Just a little ping reminder to revisit this discussion!

2024-07-17 21:52 UTC, whatisgalen commented on docs/developing/reference/search-components.rst
> +
Hi @ekansa  sorry for the delay! Lmk your thoughts or feel free to expand on my latest changes re: your comment

2024-07-18 22:24 UTC, ekansa approved these changes
Thanks @whatisgalen

2024-07-18 22:24 UTC, ekansa commented
I'm going to merge this! Thanks for the help @whatisgalen !

2024-07-18 22:24 UTC, merged