Api 7 5
archesproject/arches-docs pull request #443
Opened 2024-07-16 22:03 UTC by ekansa

### brief description of changes
I reviewed the current stable release of the API (https://github.com/archesproject/arches/blob/stable/7.5.3/arches/app/views/api.py) and the resource.py (https://github.com/archesproject/arches/blob/stable/7.5.3/arches/app/views/resource.py) source code to see if I could see where we needed to update the API documentation. 

Hopefully I caught everything!

#### issues addressed
See: (https://github.com/archesproject/arches-docs/issues/430)

#### further comments
I didn't look closely at the output examples to see if they also needed updates. I'd need an Arches instance with some public data to check that more completely.

---

This box **must** be checked
- [X] the PR branch was originally made from the base branch

This box **should** be checked
- [X] after these changes the docs build locally without error

This box **should only** be checked you intend to follow through on it (we can do it on our end too)
- [ ] I will `cherry-pick` all commits in this PR into other branches that should have them _after_ this PR is merged

2024-07-23 19:48 UTC, ekansa commented
@robgaston ping! Hopefully this update accurately reflects the current state of the API?

2024-08-01 18:17 UTC, robgaston requested changes
a nice improvement! please see a few small suggestions for changes

2024-08-01 18:17 UTC, robgaston commented on docs/developing/reference/api.rst
> +    :query nodeid: optional comma delimited list of node UUIDs to filter feature data on
the parameter name here should actually be `nodeids`.  `nodeid` still works (only for a single node id) but should be considered deprecated
```suggestion
    :query nodeids: optional comma delimited list of node UUIDs to filter feature data on
```

2024-08-01 18:17 UTC, robgaston commented on docs/developing/reference/api.rst
>      :query indent: number of spaces to indent json output
I  think that we can also indicate that the default for `indent` is `None` here
```suggestion
    :query indent: number of spaces to indent json output (default is ``None``)
```

2024-08-07 16:05 UTC, ekansa commented
Thanks @robgaston ! I committed your suggestions. Thanks for the careful review and help!

2024-08-07 16:10 UTC, robgaston approved these changes
looks good!

2024-08-07 16:18 UTC, merged