Sec 7 5
archesproject/arches-docs pull request #455
Opened 2024-08-08 23:57 UTC by ekansa

### brief description of changes
Adds a discussion of practices to help better secure Arches instances.

#### issues addressed
Discussions with the GCI about documentation gaps.

#### further comments
The updates are temporarily previewed here: https://arches.readthedocs.io/en/sec_7_5/administering/security/

---

This box **must** be checked
- [x] the PR branch was originally made from the base branch

This box **should** be checked
- [x] after these changes the docs build locally without error

This box **should only** be checked you intend to follow through on it (we can do it on our end too)
- [ ] I will `cherry-pick` all commits in this PR into other branches that should have them _after_ this PR is merged

2024-08-09 03:49 UTC, aarongundel requested changes
This is great work, Eric.  Thanks for putting all this together, I'm really happy to see this going into the docs.

2024-08-09 03:49 UTC, aarongundel commented on docs/administering/security.rst
> +The *Principle of Least Privilege* means giving any users account or processes only those privileges required to perform its intended functions, and no more. This approach helps to clarify how to man
I like this - I'm wondering though, will this cause the reader to think that default deny is "magical" and implements something at the network level to automatically deny access?  It's more precise to say that default deny will automatically deny access to **_resources_** within arches unless they are explicitly allowed.  

Also, default deny is _not_ the default, and it's important to specify this.  It has to be manually enabled.  The current plan is to force it to be the default in arches 8.

2024-08-09 03:49 UTC, aarongundel commented on docs/administering/security.rst
> +Security and Risk Management
This is a really good blurb.

2024-08-09 03:49 UTC, aarongundel commented on docs/administering/security.rst
> +* **Work in collaboration with stakeholders** to develop and implement risk reduction strategies. Understanding information security needs and risks may not be straightforward. Different stakeholders
nit: breach

2024-08-09 03:49 UTC, aarongundel commented on docs/administering/security.rst
> +* **Use strong passwords**. A strong password is a combination of characters that resists easy access by trial and error guesswork. Strong passwords provide one of the easiest to implement security m
nit: Arches typo

2024-08-09 03:49 UTC, aarongundel commented on docs/administering/security.rst
> +* **Use strong passwords**. A strong password is a combination of characters that resists easy access by trial and error guesswork. Strong passwords provide one of the easiest to implement security m
Also worth noting - enable [multifactor](https://arches.readthedocs.io/en/stable/developing/advanced/two-factor-authentication/) authentication.

2024-08-09 03:49 UTC, aarongundel commented on docs/administering/security.rst
> +* **Keep your Arches instance up-to-date**. The Arches open-source project sees continual updates and improvements. While some of these updates improve performance and capabilities, many updates also
Might be good to mention the release roadmap here, and how long versions of Arches are supported.

2024-08-09 03:49 UTC, aarongundel commented on docs/administering/security.rst
> +* **Use HTTPS on the Web**. Use of HTTPS is a critical aspect of securing your Arches instance because it encrypts and secures communications over the Web. If you do not use HTTPS, passwords and othe
It might good to be really explicit here and say "Use of HTTPS with a valid certificate." - I have seen a lot of instances that use invalid certs.  It might also be good to say that we recommend HTTPS communication between all Arches dependencies - like postgres, elasticsearch, etc.

2024-08-09 03:49 UTC, aarongundel commented on docs/administering/security.rst
> +* **Close unused ports**. In keeping with the *Principle of Least Privilege*, you should block access to all Internet ports on your servers except for those that are needed for Arches to function. Cl
It might be good to mention scoping here too.  Like for instance, "close ports and limit access to only the intended audience".  There is probably a better way to phrase this.  The idea is - you want to limit the scope of the ports you do open.  Examples:  If you know your arches instance will only ever have 5 users, consider locking down the https port to the 5 incoming IP addresses for those users.  Only expose the service ports of your postgres/es instances to your arches instance.

2024-08-09 03:49 UTC, aarongundel commented on docs/administering/security.rst
> +* **Protect your Arches system credentials**. While use of strong passwords is a key security measure, one also needs to protect the server(s) where Arches is deployed. To function, the Arches applic
This is a really good note.  It might be good to say something like "added to or accessible to these files.  You can choose to store credentials in the file itself, in the system environment variables, or, ideally, in a secret store that helps meet your cybersecurity goals, with the latter being preferred."  I am certain there's a better way to wordsmith this than what I just wrote, though.

2024-08-09 03:49 UTC, aarongundel commented on docs/administering/security.rst
> +One of the most important ways strategies to improve Arches security centers on collaboraiton with the larger Arches open-source community. Some organizations, particularly those in the public sector
We're trying to avoid advertising security issues in the github tracker, as that provides a roadmap to attack existing Arches installations.  It's better that we put an email or point of contact here - we have a separate, private tracker arches for security issues.

2024-08-09 04:36 UTC, aarongundel commented
Might also be good to mention encrypted storage - file storage, disk storage, etc.

2024-08-09 18:17 UTC, ekansa commented on docs/administering/security.rst
> +The *Principle of Least Privilege* means giving any users account or processes only those privileges required to perform its intended functions, and no more. This approach helps to clarify how to man
OK! I added a clarification about default deny. Thanks for the additional info @aarongundel !

2024-08-09 18:18 UTC, ekansa commented on docs/administering/security.rst
> +* **Work in collaboration with stakeholders** to develop and implement risk reduction strategies. Understanding information security needs and risks may not be straightforward. Different stakeholders
thanks!

2024-08-09 18:27 UTC, ekansa commented on docs/administering/security.rst
> +* **Use strong passwords**. A strong password is a combination of characters that resists easy access by trial and error guesswork. Strong passwords provide one of the easiest to implement security m
Excellent point @aarongundel. I added a point and a reference to that documentation.

2024-08-09 18:59 UTC, ekansa commented on docs/administering/security.rst
> +* **Use HTTPS on the Web**. Use of HTTPS is a critical aspect of securing your Arches instance because it encrypts and secures communications over the Web. If you do not use HTTPS, passwords and othe
That's helpful. I added a note about valid certificates and a pointer to Let's Encrypt.

2024-08-09 20:26 UTC, ekansa commented on docs/administering/security.rst
> +* **Close unused ports**. In keeping with the *Principle of Least Privilege*, you should block access to all Internet ports on your servers except for those that are needed for Arches to function. Cl
Done

2024-08-09 20:32 UTC, ekansa commented on docs/administering/security.rst
> +* **Protect your Arches system credentials**. While use of strong passwords is a key security measure, one also needs to protect the server(s) where Arches is deployed. To function, the Arches applic
OK I added this

2024-08-09 21:25 UTC, ekansa commented
> Might also be good to mention encrypted storage - file storage, disk storage, etc.

Good idea! I added a point about this.

2024-08-09 21:39 UTC, aarongundel commented on docs/administering/security.rst
> +* **Consider encrypted storage**. As an extra security measure, one can encrypt storage systems used by Arches. For example, if Arches is used to manage uploads of digital files (image files, GIS fil
"stored in a PostgreSQL database or elasticsearch"

2024-08-09 22:11 UTC, ekansa commented on docs/administering/security.rst
> +* **Consider encrypted storage**. As an extra security measure, one can encrypt storage systems used by Arches. For example, if Arches is used to manage uploads of digital files (image files, GIS fil
Perfect! Thanks!

2024-08-10 20:10 UTC, aarongundel approved these changes
LGTM

2024-08-11 23:30 UTC, merged