Added more explanation of apps in intro, more specifics in applicatio…
archesproject/arches-docs pull request #470
Opened 2024-11-07 01:17 UTC by ekansa

…n section

### brief description of changes
This is just a start to get some feedback, but is not at all ready for merging.

#### issues addressed
Our conversation about Arches applications and how to explain their significance in developer guidance.

#### further comments
Please review and consider with @apeters 's proposed forum post. I think I'm covering some of the points, but may be garbling some of this. It would be great to provide some specifics about how to make a new Arches Application (starting from a project, right?). I read about how Django does it but the terminology seems to differ from Arches terminology a little. Anyway, those terminology issues should be an important topic for review.

---

This box **must** be checked
- [ ] the PR branch was originally made from the base branch

This box **should** be checked
- [ ] after these changes the docs build locally without error

This box **should only** be checked you intend to follow through on it (we can do it on our end too)
- [ ] I will `cherry-pick` all commits in this PR into other branches that should have them _after_ this PR is merged

2024-11-13 01:23 UTC, apeters requested changes

2024-11-13 01:23 UTC, apeters commented on docs/developing/getting-started/customization-considerations.rst
> +
```suggestion
```

2024-11-13 01:23 UTC, apeters commented on docs/developing/getting-started/customization-considerations.rst
```suggestion

Arches Applications
=======================
While the Arches extensions (see above) architecture offers a great deal of flexibility, there may be scenarios where you need additional flexibility. From a sustainability and maintenance perspective, ideally you should isolate your customized module as much as possible from the core of Arches. One way to accomplish this is to develop an  **Arches Application** (see: :ref:`Creating Applications`), which are discrete Python packages that can be integrated into one or more Arches projects. The **Arches Applications** documentation details their development as well as their sustainability advantages.

Arches Applications are a powerful way to create customizations that are isolated from the core of Arches. This isolation can help to reduce the risk of future maintenance and upgrade challenges. Arches Applications create reusable components that can be developed and maintained independently of the core Arches software, and can be shared with the wider Arches community. This can help to ensure that your customizations are more maintainable over time and can help to reduce the overall cost of development and maintenance.
```

2024-11-13 01:23 UTC, apeters commented on docs/developing/getting-started/customization-considerations.rst
> +Customization of Simple Extensions
```suggestion
Custom Extensions
```

2024-12-05 00:42 UTC, ekansa commented
@apeters I got back to this and incorporated your changes, and fixed a few style issues. This is temporarily viewable here: https://arches.readthedocs.io/en/applications_7_6/developing/extending/creating-apps/

2024-12-11 00:19 UTC, merged

2024-12-11 00:20 UTC, ekansa commented
Merging this, because it's better than what we already had! We can return to this to make additional improvements.